server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
          - hystrix.stream

spring.boot.admin.client.url: http://localhost:8093


spring:
  application:
    name: cloud-gateway