spring:
  application:
    name: config-server
#  cloud:
#    bus:
#      enabled: true
#    stream:
#      kafka:
#        binder:
#          zkNodes: localhost:9092,127.0.0.1:9092
#          brokers: localhost:2181,127.0.0.1:2181

server:
  port: 8888

spring.cloud.config.server.git.uri: file://F:/workspace/MICROSERVICES/spring-boot-microservices-eureka/git-repo


management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
          - 'bus-refresh'
